### ISSUE TITLE
Rebuilding Linux VM Image

### ISSUE THREAD

**Issue by bri451** [SEL4PROJ/camkes-arm-vm#1]
Hello, 

I'm trying to rebuild the checked in Linux VM image forked from Buildroot. I'm using the included buildroot_tk1_defconfig settings, but these are pointing to a set of kernel files at "/scratch/armvm/projects/linux-tegra". Is this directory checked into a repo anywhere? Other settings (BR2_LINUX_KERNEL_DEFCONFIG="tegra_sel4vm") make this appear to be a custom versioned kernel, and not the kernel provided directly by Nvidia. Any further info would be appreciated.

**Comment by kent-mcleod** [comment]
Hi,
We used a custom version based on mainline Linux 4.3-rc5.  I am in the process of making the source available.  I'll comment with a link when this happens.

**Comment by kent-mcleod** [comment]
You can find the version of Linux we used here: https://github.com/SEL4PROJ/linux-tegra/commits/sel4

**Comment by bri451** [comment]
Thanks!
