### ISSUE TITLE
Old README

### ISSUE THREAD

**Issue by pjr2442** [SEL4PROJ/camkes-arm-vm#2]
The README seems to be out of date, and references buildroot directories and files that no longer seem to be in the project repo. I'm looking to use this repo to build out the advertised Debian VM on a tegra TK1 platform, and am new to the seL4-scene -- can someone help out and update the README and other documentation?

Thanks

**Comment by kent-mcleod** [comment]
Thanks for letting us know.  I updated it internally and it should get pushed out in the next few hours. What changed is that we stopped using .dtb binary files for the device tree configuration and started using dts source files (making it easier to configure what devices linux expects to be given).

**Comment by danielwangksu** [comment]
Buildroot 2016.08.1 does not work with current Linux-Tegra repository. The current repo requires kernel headers 4.90. Based on my test Buildroot 2017.02.01 works. Other new version may not work due to legacy configuration in buildroot_tk1_initrd_defconfig
