### ISSUE TITLE
VChan Option Broken/Outdated

### ISSUE THREAD

**Issue by chrisguikema** [SEL4PROJ/camkes-arm-vm#3]
I am trying to use the menuconfig to enable the Virtual Channel on the odroid version, and there are quite a few steps required to get it functional. (I am using the master branch of the camkes-tool).

First, the `libsel4vchan` is not a Kbuild dependency, so even when the menuconfig option to build the library is selected, it doesn't compile and the application compilation fails.

Second, the `libsel4arm-vmm` config option doesn't automatically update to include Vchan support, so the additional items in the `vm_t` structure don't get updated.

`VM.camkes` needs `include "sel4vchan/vchan_sharemem.h";` since the `vchan_sharemem.h` link in the `src` directory is broken, along with `vchan_copy.h`.

Finally, `vchan.c` and `cmks_vchan_vm.c` need the `VM.h` and `Vchan.h` updated to `camkes.h` since CAmkES 3.1 doesn't generate component-named header files anymore.

I don't know if the Virtual Channel feature actually gets used, but it would be nice to have some documentation outlining the required menuconfig steps and how to system is structured. I've attached my [defconfig](https://github.com/SEL4PROJ/camkes-arm-vm/files/1416056/vm_vchan_defconfig.zip) incase you want to add a new config option

**Comment by AdrianDanis** [comment]
Hi @chrisguikema 
Sorry for the delay. The vchan implementation in the arm VMM was not really used and I cannot say why the partial implementation ended up there. Although sounds like you managed to get it into a working state. The [x86 CAmkES VMM](https://github.com/seL4/camkes-vm) made more use of vchan, although it doesn't have anything more in the way of documentation at the moment.
