### ISSUE TITLE
map_unity_ram: Failed to map page 0x68254000

### ISSUE THREAD

**Issue by chengshuyi** [SEL4PROJ/camkes-arm-vm#5]
I have configured **LINUX_RAM_PADDR_BASE** to 0x50000000 and **LINUX_RAM_SIZE** to 0x20000000. However it caused an error : `Failed to map page 0x68254000`. 

If i change **LINUX_RAM_SIZE** to 0x100000000, it would be ok.

If i change **LINUX_RAM_PADDR_BASE** to 0x60000000 and **LINUX_RAM_SIZE** to 0x20000000, it would also caused an error  : `Failed to map page 0x78254000`.  It seems like the **LINUX_RAM_SIZE** cant exceed 0x18254000.

It is confusing. Thanks for any advice!

**Comment by WellMcGarnicle** [comment]
Hey @chengshuyi 
That error seems to occur when `map_unity_ram` tries to perform a utspace alloc. May I ask what platform you are compiling for?

**Comment by chengshuyi** [comment]
Hi @WellMcGarnicle 

Yes, it is. The error code is:

```
        err = vka_utspace_alloc_at(vm->vka, &frame, kobject_get_type(KOBJECT_FRAME, bits), bits, start, &cookie);
        if (err) {
            printf("Failed to map ram page 0x%lx\n", (long unsigned int)start);
            vka_cspace_free(vm->vka, frame.capPtr);
            break;
        }
```

The platform is imx8mq evk, cortex-a53 processors. Because imx8mq doesn't have IOMMU, i tried to use **map_unity_ram** to support pass-through ethernet.

**Comment by WellMcGarnicle** [comment]
Is the memory region you are allocating defined in the kernel device tree? for example we overlay the exynos5422 dts (https://github.com/seL4/seL4/blob/master/src/plat/exynos5/overlay-exynos5422.dts#L36) with the memory region (which is also used for `map_unity_ram`) to ensure that it is made available.

**Comment by chengshuyi** [comment]
I'm using old sel4 kernel which version use **dev_p_regs** to declare device memory region. And adding memory region {0x50000000,0x50000000+0x80000000} to it.

**Comment by lsf37** [comment]
Closing this, because this repo is deprecated and about to be archived. The ARM virtual machine implementation now lives in https://github.com/seL4/camkes-vm
