### ISSUE TITLE
Will the project will support zynqmp VM ？

### ISSUE THREAD

**Issue by lydmcu** [SEL4PROJ/camkes-arm-vm#7]
hi，
    Will arm-vm will support zynqmp platform ？
                                                                  3x

**Comment by kent-mcleod** [comment]
@lydmcu: It will -- there are pending PRs on this repo that adds support which we plan to get merged before the end of the year.  You can see [here](https://github.com/dornerworks/sel4-armv8-vmm-manifest) for a version by Dornerworks that targets a 2017.3 version of petalinux .

**Comment by lydmcu** [comment]
OK，Thank you very much.
