### ISSUE TITLE
Features Tables Says QEMU VirtIO Console is supported....init does not

### ISSUE THREAD

**Issue by jimshift5** [SEL4PROJ/camkes-arm-vm#9]
When I try to build vm_serial_server for qemu-arm-virt I get the output below [1]. The features table in the README indicates that VirtIO Console is supported for QEMU Virt is this something on y'alls internal github that hasn't made it out or is the table wrong?

For giggles I moved the qemu-arm-virt with its device.cmakes into the serial-server and flipped settings.cmake to support it...obviously that didn't work :-)

[1]
user@user-dev:~/Documents/labs/rr/os/seL4-AUS/camkes-arm-vm/build-vm_serial_server$ ../init-build.sh -DCAMKES_VM_APP=vm_serial_server -DPLATFORM=qemu-arm-virt
loading initial cache file /home/user/Documents/labs/rr/os/seL4-AUS/camkes-arm-vm/projects/vm/settings.cmake
CMake Error at apps/vm_serial_server/settings.cmake:15 (message):
  PLATFORM: qemu-arm-virt not supported.

           Supported: exynos5422
Call Stack (most recent call first):
  settings.cmake:61 (include)

-- Configuring incomplete, errors occurred!

**Comment by lsf37** [comment]
Closing this, because this repo is deprecated and about to be archived. The ARM virtual machine implementation now lives in https://github.com/seL4/camkes-vm
